#include<iostream.h>
#include<conio.h>


			 //CLASS 1 EXAMPLE OF TABLE


/*class sum
{
  public:
	  table()
	{
	   int n,i,tab=0;
	   cout<<"Enter number for table:\n";
	   cin>>n;
	   for(i=1;i<=10;i++)
	   {
	     tab = n * i;
	     cout<<tab<<"\n";
	     }
	     }
	     };

    void main()
    {
      sum ob;
      clrscr();
      ob.table();
      getch();
      } */


  /*  class example
  {
    private :
    {
      int somedata;
     }
    public :

    void setdata(int p)
    {
      somedata = p;
      }
     void showdata()
     {
     cout<<"="<<somedata;
     }
     };


   void main()

   {
     example ob;
     int a;
     clrscr();
     cin>>a;
     ob.setdata(a);
     ob.showdata() ;
     getch();
     }   */


    /* class employee
    {
       private :
	    int id;
	    char name[10];
	    float sal;
	void getemp()
	{
	   cout<<"Enter id,name & salary of emp\n";
	   cin>>id>>name>>sal;
	   }

       public:

	void showemp()
	{
	  getemp();
	  cout<<"\n\tDetails\n";
	  cout<<id<<"\n"<<name<<"\n"<<sal<<"\n";
	  }
	  };


  void main()
  {
    employee ob;
    clrscr();
    ob.showemp();
    getch();
    }  */


