#include<iostream.h>
#include<conio.h>


	      //BREAK THE LOOP EXAMPLE


/*void main()
{
  int i;
  clrscr();
  for(i=0;i<5;i++)
  {
   if(i==3)
   {
   break;
   }
   cout<<i<<"\n";
   }
   getch();
   }*/



//EXAMPLE OF CONTINUE IN LOOP BY IGNORE THE IF NUMBER AND PRINT OTHER NUMBERS



/* void main()
 {
  int i;
  clrscr();
  for(i=1;i<=10;i++)
  {
  if(i==2 || i==4 || i==6 || i==8 || i==10)
  {
  continue;
  }
  cout<<i<<"\n";
  }
  getch();
  }*/