#include<iostream.h>
#include<conio.h>

/*void main()
{
 int a[3][3],b[3][3],i,j;
 int c[3][3],option;
 clrscr();
 cout<<"Enter the matrix of A:\n";
 for(i=0;i<3;i++)
 {
  for(j=0;j<3;j++)
  {
  cin>>a[i][j];
  }
  }
  cout<<"Enter the matrix of B:\n";
  for(i=0;i<3;i++)
  {
  for(j=0;j<3;j++)
  {
  cin>>b[i][j];
  }
  }
  for(i=0;i<3;i++)
  {
  for(j=0;j<3;j++)
  {
    c[i][j] = 0;
    }
    }

 cout<<"Select the option:\n";
 cout<<"1.Plus"<<endl;
 cout<<"2.Minus"<<endl;
 cin>>option;

 switch(option)
 {
    case 1:

	 clrscr();
	 for(i=0;i<3;i++)
	 {
	 for(j=0;j<3;j++)
	 {

	 c[i][j] = a[i][j] + b[i][j];
	 }
	 }
	 for(i=0;i<3;i++)
	 {
	 for(j=0;j<3;j++)
	 {
	   cout<<" "<<c[i][j];
	   }
	   cout<<endl;
	   }
	   break;

     case 2:
	      clrscr();
	      for(i=0;i<3;i++)
	      {
	      for(j=0;j<3;j++)
	      {
	      c[i][j]=a[i][j] - b[i][j];
	      }
	      }
	      for(i=0;i<3;i++)
	      {
	      for(j=0;j<3;j++)
	      {
	      cout<<" "<<c[i][j];
	      }
	      cout<<endl;
	      }
	      break;
	      }*/
























  getch();
  }

