#include<iostream.h>
#include<conio.h>

 // IN THIS EXAMPLE TAKE OBJECT ARRAY AND CONTROL THE EACH ELEMENTS POSITION BY
 // POINTER.


/*class example
{
   int num;

   public:
      void entval(int val)
      {
	num = val;
	}

      void showval()
      {
	cout<<num<<endl;
	}
	};

  void main()
  {
    example ob[2] , *objectpointer;
    clrscr();
    ob[0].entval(10);
    ob[1].entval(20);

    objectpointer = &ob[0];
    objectpointer -> showval();

    objectpointer++;
    objectpointer -> showval();

    objectpointer--;
    objectpointer -> showval();




    getch();
    }*/



