#include<stdio.h>
#include<conio.h>
void main()
{/*int a,b,c=1;
clrscr();
printf("Enter the factorial:");
scanf("%d",&a);
b=1;

do
{
c=c*b;
b++;


}

while(b<=a);
printf("%d\n",c);   */



/*int i,n=4,m,j,k;
clrscr();
for(i=1;i<=n;i++)
{
      printf("\n");
	 for(j=n-i;j>=1;j--)
     {   printf(" ");}
     printf("*");
     m=0;
     for(k=i;k>(2*m+1);k++)
     {         printf("#*");
	       m++;
			  }
			     }
    for(i=n-1;i>=1;i--)
    {       printf("\n");
	    for(j=0;j<n-i;j++)
	    {
	     printf(" ");
	     }
	     printf("*");
	     for(k=1;k<i;k++)
	     { printf("#*");
	     }
	     } */






getch();
}