#include<stdio.h>
#include<conio.h>
void main()
{                            //series
			     //For loop
/*int i,a;
clrscr();
printf("Enter the Value of a=\n");
scanf("%d",&a);
for (i=1;i<=a;i=i+1)
{
printf("=%d\n",i);
}
getch();*/
		  //table

/*int i,a;
clrscr();
printf("Enter the value for A=\n");
scanf("%d",&a);
for (i=1;i<=10;i=i+1)
{  printf("%d*%d=%d\n",a,i,a*i);
}
getch();*/
			      //example of table


/*int i,a;
clrscr();
printf("Enter the value for A=\n");
scanf("%d",&a);
for (i=1;i<=20;i=i+1)
{ printf("->%d*%d=%d\n",a,i,a*i);
}
getch(); */
			   //CGPA calculator

/*float a,p;
clrscr();
printf("Enter your CGPA/SPA/CPI=\n");
scanf("%f",&a);
p=(a-0.5)*10;
printf("Your percentage is=\n");
printf("->%.2f",p);
getch();*/
			       //Customary Conversions
/*float m,f,s;
clrscr();
printf("Enter the value of Mile=\n");
scanf("%f",&s);
m=5280.0*s;
printf("your answer in feet is=\n");
printf("=%.1f\n",m);
getch();*/
			      //Metric Conversion

/*float m,s;
clrscr();
printf("Enter the value of Kilometer=\n");
scanf("%f",&s);
m=(1000.0)*s;
printf("Your answer in meter is=\n");
printf("=%.1f\n",m);
getch();*/

int m,s;
clrscr ();
printf("Enter the numbers of months=\n");
scanf("%d",&s);
m=(30*s);
printf("answer=\n");
printf("%d\n",m);
getch();

}
