#include<stdio.h>
#include<conio.h>
void main()
{/*                          // Pythagoras
 int a,b,c;
clrscr();
printf("Enter the Value of A-\n");
scanf(  "%d",&a);
printf("Enter the Value of B-\n");
scanf(  "%d",&b);
c=((a*a)+(b*b));
printf("Your Answer is=\n");
printf("%d",c);
getch();*/
		    //Perimeter & Area Sum
/*int p,a,l,w ;
clrscr();
printf("Enter the length\n");
scanf("%d",&l);
printf("Enter the Width\n");
scanf("%d",&w);
p=((2*l)+(2*w));
a=l*w;
printf("The value of P is=\n");
printf("%d\n",p);
printf("And Area A is=\n");
printf("%d\n",a);
getch();*/
			  //sum no.3
/*float z,a,b,h;
clrscr();
printf("Enter the Value of a=\n");
scanf("%f",&a);
printf("Enter the Value of b=\n");
scanf("%f",&b);
printf("Enter the Value of h=\n");
scanf("%f",&h);
z=(0.5*h*(a+b));
printf("Your Answer is\n");
printf("%.2f\n",z);
getch();*/
			   //sum 04
/*float a,b,h,p,c,d;
clrscr();
printf("Enter the Value of b=\n");
scanf("%f",&b);
printf("Enter the Value of c=\n");
scanf("%f",&c);
printf("Enter the Value of d=\n");
scanf("%f",&d);
printf("Enter the value of h=\n");
scanf("%f",&h);
a=(0.5)*b*h;
p=b+c+d;
printf("Your answer for A=\n");
printf("=%.2f\n",a);
printf("Your answer for P=\n");
printf("=%.2f\n",p);
getch();*/
				//sum no.5

/*float a,c,r;
clrscr();
printf("Enter the value of radius=\n");
scanf("%f",&r);
c=(2*3.14*r);
a=(3.14*(r*r));
printf("Your answer c is=\n");
printf("=%.2f\n",c);
printf("Your answer a is=\n");
printf("=%.2f\n",a);
getch();*/
			     //sum 6
/*int s,v,z;
clrscr();
printf("Enter the Value s=\n");
scanf("%d",&s);
z=(6)*(s*s);
v=s*s*s;
printf("Your Answer for z is=\n");
printf("=%d\n",z);
printf("Your Answer for v is=\n");
printf("=%d",v);
getch();*/
			       //sum 7

/*int w,l,h,v,z;
clrscr();
printf("Enter the Value of w=\n");
scanf("%d",&w);
printf("Enter the Value of l=\n");
scanf("%d",&l);
printf("Enter the value of h=\n");
scanf("%d",&h);
z=(2*(l*w)+2*(l*h)+2*(w*h));
v=l*w*h;
printf("Your answer for z=\n");
printf("%d\n",z);
printf("Your answer for v=\n");
printf("%d\n",v);
getch();*/
			       //sum of degree in polygon
/*float d,n;
clrscr();
printf("Enter the Number of sides n=\n");
scanf("%f",&n);
d=(180*(n-2));
printf("Your Answer is=\n");
printf("%.1f",d);
getch();*/

float c,f;
clrscr();
printf("Enter the Value of F=\n");
scanf("%f",&f);
c=((5/9)*(f-32));
printf("=%f\n",c);
printf("Enter the Value of C=\n");
scanf("%f",&c);
f=((9/5)*(c+32));
printf("=%f\n",f);
getch();

}





