#include<stdio.h>
#include<conio.h>
#define colmax 10
#define rowmax 12

main()
{  /* int row,column,y;
    clrscr();
    row =1;
    printf("    \tmultiplication table     \n");
    printf("--------------------------------------------\n");
    do
    {  column = 1;

    do
    {
	y = row * column;
	printf("%4d",y);
	column = column + 1; }

    while (column <= colmax);
    printf("\n");
    row = row+1;
		  }
    while (row <= rowmax);
    printf("--------------------------------------------\n");  */


    getch();
    return 0;   }