#include<stdio.h>
#include<conio.h>

void main()
{
		      //while statement example
/*int a,b,y,c;
clrscr();
printf("Enter the number:-\n");
scanf("%d",&a);
printf("Enter the power:-\n");
scanf("%d",&b);
y=1;
c=1;
while (c<=b)
{ y= y*a;
c++;
}
printf("=%d",y); */


			 //while example with for loop
/*int a,b,c,y;
clrscr();
printf("Enter the number:-\n");
scanf("%d",&a);
printf("Enter the power:-\n");
scanf("%d",&b);
y=1;
for(c=1;c<=b;c++)
{
    y=y*a;
    }
    printf("%d",y);  */




getch();
}