#include<stdio.h>
#include<conio.h>
void main()
{
/*float amount,value,intrest,year,period;
clrscr();
printf("Enter the amount:\n");
scanf("%f",&amount);
printf("Enter the rate of intrest:\n");
scanf("%f",&intrest);
printf("Enter the period of time:\n");
scanf("%f",&period);
while (year<=period)

{
value=amount+intrest*amount;
year++;
printf("Rs %f\n",value);
			   } */


/*long sum=0L;
int i=1;
int count =0;
clrscr();

printf("\nEnter the number of integers you want to sum: ");
scanf(" %d",&count);

while(i<=count)
{
   sum+= i++;}
   printf("Total of the first %d numbers is %ld\n",count,sum);*/

/*long sum=1l;
int j=1;
int count =10;
int i;
clrscr();
for(i=1;i<=count;i++)
{   sum=1l;
    j=1;

   printf("\n1");

while(j<i){
sum+=++j;
printf("+%d",j);
}
printf(" = %ld\n",sum);}

*/






getch();}
